import '@/styles/globals.scss';
import 'react-toastify/dist/ReactToastify.css';

import { NextPage } from 'next';
import { AppProps } from 'next/app';
import Head from 'next/head';
import { ReactElement, ReactNode } from 'react';
import { ErrorBoundary } from 'react-error-boundary';
import { Provider } from 'react-redux';
import { ToastContainer } from 'react-toastify';

import ClientOnly from '@/components/ClientOnly';
import { DefaultErrorState } from '@/components/DefaultErrorState';
import { AuthProvider } from '@/context/AuthContext';
import store from '@/store';

export type NextPageWithLayout = NextPage & {
  getLayout?: (page: ReactElement) => ReactNode;
};

type AppPropsWithLayout = AppProps & {
  Component: NextPageWithLayout;
};

export default function App({ Component, pageProps }: AppPropsWithLayout) {
  const getLayout = Component.getLayout ?? ((page) => page);
  return (
    <>
      <Head>
        <title>Vending Machine</title>
        <meta name="description" content="Generated by Enes Kaya" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ErrorBoundary FallbackComponent={DefaultErrorState}>
          <AuthProvider>
            <Provider store={store}>
            <ClientOnly>
              <ToastContainer />
              {getLayout(<Component {...pageProps} />)}
              </ClientOnly>
            </Provider>
          </AuthProvider>
        </ErrorBoundary>
      </main>
    </>
  );
}
