name: "Auto Assign"
on:
  pull_request:
    types: [opened, ready_for_review]
    branches:
      - main

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.2.0
