name: Deploy develop to heroku

on:
  push:
    branches:
      - develop

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_ORG_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_ORG_EMAIL}}
        env:
          HD_NEXT_PUBLIC_ENV: ${{secrets.ENV_DEV}}
          HD_NEXT_PUBLIC_BACKEND_API_URL: ${{secrets.BACKEND_API_URL_DEV}}
